name: 'Build'

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        config:
          - runner: ubuntu-latest
            goos: linux
            goarch: amd64
            suffix: ''
          - runner: ubuntu-24.04-arm
            goos: linux
            goarch: arm64
            suffix: ''
          - runner: ubuntu-latest
            goos: windows
            goarch: amd64
            suffix: '.exe'
          - runner: ubuntu-24.04-arm
            goos: windows
            goarch: arm64
            suffix: '.exe'
          - runner: macos-latest
            goos: darwin
            goarch: arm64
            suffix: ''
          - runner: macos-latest
            goos: darwin
            goarch: amd64
            suffix: ''
    runs-on: ${{ matrix.config.runner }}
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v6
      - name: 'Setup go'
        uses: actions/setup-go@v6
        with:
          go-version-file: 'go.mod'
      - name: 'Build'
        env:
          CGO_ENABLED: 0
          GOOS: ${{ matrix.config.goos }}
          GOARCH: ${{ matrix.config.goarch }}
        run: 'go build -o http-echo${{ matrix.config.suffix }}'
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v7
        with:
          name: 'http-echo-${{ matrix.config.goos }}_${{ matrix.config.goarch }}${{ matrix.config.suffix }}'
          path: 'http-echo${{ matrix.config.suffix }}'